export default {
    profile: require('../assets/images/profile.png'),
    rightArrow: require('../assets/images/rightArrow.png'),
    calenderImage: require('../assets/images/calenderImage.png'),
    leftArrow: require('../assets/images/leftArrow.png'),
    crossImage: require('../assets/images/crossImage.png'),
    googleImage: require('../assets/images/google.png'),
    facebookImage: require('../assets/images/facebook.png'),
    carousal: require('../assets/images/practo1.jpg'),
    peanut: require('../assets/images/practo2.jpg'),
    nitro: require('../assets/images/practo3.jpg'),
    logo: require('../assets/images/practo5.jpg'),
    cart: require('../assets/images/cart.png'),
    menu: require('../assets/images/menuIcon.png'),
    logo1: require('../assets/images/download1.png'),
    slider1: require('../assets/images/practo1.webp'),
    slider3: require('../assets/images/practo2.webp'),
    slider5: require('../assets/images/practo3.webp'),
    item1: require('../assets/images/blood_sugar.webp'),
    item2: require('../assets/images/lipid_profile.webp'),
    item3: require('../assets/images/liver_profile.webp'),
    item4: require('../assets/images/thyroid.png'),
    item5: require('../assets/images/pregnancy.png'),
    item6: require('../assets/images/fever.png'),
    item7: require('../assets/images/item7.jpeg'),
    item8: require('../assets/images/item8.jpeg'),
    shoppingBag: require('../assets/images/shopingBag.png'),
    sentImage: require('../assets/images/sentImage.png'),
    heartImage: require('../assets/images/heartImage.png'),
    search: require('../assets/images/search.png'),
    sent: require('../assets/images/sent.png'),
    plus:require('../assets/images/plus.png'),
    appointment:require("../assets/images/appointment.png"),
    doctor:require("../assets/images/doctor.png"),
    home:require("../assets/images/home.png"),
    chat:require("../assets/images/chat.png"),
    test:require('../assets/images/test.png')
}